export const SEGMENTS = {
  mailable: { label:'Send list', note:'Confirmed deliverable, plus role addresses that carry no other risk.',
    filter:'or=(status.eq.safe,and(status.eq.risky,role_account.is.true,catch_all.is.false,disposable.is.false,full_inbox.is.false))' },
  deliverable: { label:'Confirmed, no role', note:'Confirmed deliverable with info@, hello@ and similar removed.',
    filter:'status=eq.safe&role_account=is.false' },
  safe_all: { label:'Confirmed', note:'Everything the mail server confirmed, role addresses included.',
    filter:'status=eq.safe' },
  role: { label:'Role addresses', note:'info@, support@, contact@ and the like.',
    filter:'role_account=is.true' },
  catch_all: { label:'Catch-all', note:'The domain accepts anything, so the mailbox cannot be confirmed either way.',
    filter:'catch_all=is.true' },
  unresolved: { label:'No answer', note:'The mail server would not say. Worth a second pass or a paid check.',
    filter:'status=in.(unknown,error)' },
  invalid: { label:'Suppress', note:'Confirmed undeliverable. Feed this back into your sending platform.',
    filter:'status=eq.invalid' },
  disposable: { label:'Disposable', note:'Throwaway inbox providers.',
    filter:'disposable=is.true' },
  full_inbox: { label:'Full inbox', note:'Real address, but the mailbox is over quota.',
    filter:'full_inbox=is.true' },
};
export const SEGMENT_ORDER = ['mailable','deliverable','safe_all','role','catch_all','unresolved','invalid','disposable','full_inbox'];
